### PR TITLE
Add "improvement" type as suggested by the spec

### PR DESCRIPTION
**Pull request by binarylogic**
From the [spec](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary):

> We also recommend improvement for commits that improve a current implementation without adding a new feature or fixing a bug.

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks! Appreciate the quick turn around.

Think we can get a version bump? We'd like to include these changes in the Github semantic pull request bot:

https://github.com/probot/semantic-pull-requests

**Comment by AndersDJohnson** [comment]
@binarylogic I've now published to `npm` as `2.3.0`. Thanks!

**Comment by matthewfeickert** [comment]
@AndersDJohnson Would you also be willing to cut a GitHub release? Not sure, but that might affect the [`probot/semantic-pull-requests` issue I filed](https://github.com/probot/semantic-pull-requests/issues/72) related to `commitizen/conventional-commit-types` type releases.

**Comment by AndersDJohnson** [comment]
@matthewfeickert Sure, I just pushed the tag for `v2.3.0` and also created GitHub release (https://github.com/commitizen/conventional-commit-types/releases/tag/v2.3.0).

Note that historically we've pushed tags here but not necessarily created GitHub releases out of them. Will that be a problem for your tooling?

**Comment by matthewfeickert** [comment]
> @matthewfeickert Sure, I just pushed the tag for `v2.3.0` and also created GitHub release (https://github.com/commitizen/conventional-commit-types/releases/tag/v2.3.0).

Thanks very much! I appreciate you being so responsive.

> Note that historically we've pushed tags here but not necessarily created GitHub releases out of them. Will that be a problem for your tooling?

Good question. I'm not actually sure, as I just gave a cursory glance and noticed that this PR was quite recent when I was reporting my issue to the `probot/semantic-pull-requests` team, so I thought I'd ask just to be safe and to make things easier to compare as they cite `commitizen/conventional-commit-types` `v2.2.0` on GitHub in their `README`. At the risk of being annoying I'll tag @zeke here as they seem to be the one who has committed to `probot/semantic-pull-requests` [the most in 2019](https://github.com/probot/semantic-pull-requests/graphs/contributors). 

Though at this point as you've been so helpful I think that any discussion on this PR can stop and that any follow up can just be [on the Issue I made](https://github.com/probot/semantic-pull-requests/issues/72). Thanks again! :)

**Comment by AndersDJohnson** [comment]
@binarylogic @matthewfeickert It looks like they removed `improvement` as recommended. It was [in their `1.0.0-beta.4` release](https://github.com/conventional-commits/conventionalcommits.org/blame/a3f54496f57dfaf831447e21cd4c43a9cd7fc84e/content/v1.0.0-beta.4/index.md#L39), but [removed in `1.0.0`](https://github.com/conventional-commits/conventionalcommits.org/blame/a3f54496f57dfaf831447e21cd4c43a9cd7fc84e/content/v1.0.0/index.md#L42).

I'm proposing we consider removing it in https://github.com/commitizen/conventional-commit-types/pull/16, so I would appreciate if you could share thoughts there.

**Comment by binarylogic** [comment]
👍 Go for it. I don't have strong opinions. We're able to customize our PR check to allow for custom types.

**Comment by matthewfeickert** [comment]
@AndersDJohnson Thanks very much for the heads up. This all sounds fine to me, so I'll adjust things on the pyhf side accordingly.

**Pull request merged**
